Comply with `shfmt`

diff --git a/transcrypt b/transcrypt
--- a/transcrypt
+++ b/transcrypt
@@ -122,7 +122,7 @@ _validate_variable_str() {
 		if [[ $interactive ]]; then
 			_set_global "$varname" ""
 			echo "$message"
-            return 1
+			return 1
 		else
 			die 1 "$message"
 		fi
@@ -152,7 +152,7 @@ _get_user_input() {
 			${validate_fn}
 		fi
 	done
-    ${validate_fn} || die "Invalid setting"
+	${validate_fn} || die "Invalid setting"
 }
 
 # Check if the first arg is contained in the space separated second arg
@@ -213,8 +213,8 @@ _load_config_var() {
 	# (which is expected to be stored in plaintext and checked into the repo)
 	# Certain values will be blocked from being placed here (like the password)
 	local key=$1
-	_load_unversioned_config_var "${key}" || \
-        ([[ "$USE_VERSIONED_CONFIG" == "1" ]] && _load_versioned_config_var "${key}")
+	_load_unversioned_config_var "${key}" ||
+		([[ "$USE_VERSIONED_CONFIG" == "1" ]] && _load_versioned_config_var "${key}")
 }
 
 _set_config_var() {
@@ -237,8 +237,8 @@ _load_transcrypt_config_vars() {
 	openssl_path=$(_load_config_var "transcrypt.openssl-path") || (echo "failed to load transcrypt.openssl-path" && false)
 	password=$(_load_unversioned_config_var transcrypt.password) || (echo "failed to load transcrypt.password" && false)
 	ensure_salt_method
-    validate_kdf || die "invalid value of kdf in config"
-    validate_digest || die "invalid value of digest in config"
+	validate_kdf || die "invalid value of kdf in config"
+	validate_digest || die "invalid value of digest in config"
 }
 
 _load_vars_for_encryption() {
@@ -719,7 +719,7 @@ save_helper_scripts() {
 		# Editable mode is for debugging
 		ln -fs "$current_transcrypt" "${CRYPT_DIR}/transcrypt"
 	else
-        rm -f "${CRYPT_DIR}/transcrypt"  # unlink if it already exist 
+		rm -f "${CRYPT_DIR}/transcrypt" # unlink if it already exist
 		cp -f "$current_transcrypt" "${CRYPT_DIR}/transcrypt"
 	fi
 	# make scripts executable
