if CDPATH is set, then cd will print the path (#156)
Thanks for the contribution @andreineculau 

I never knew the `CDPATH` option existed. I can't see myself ever using it, but with your change anyone with it enable will get much less junk printed out from transcrypt.

diff --git a/transcrypt b/transcrypt
--- a/transcrypt
+++ b/transcrypt
@@ -56,10 +56,10 @@ realpath() {
 	# canonicalize path
 	local dirname=
 	if [[ -d $abspath ]]; then
-		dirname=$(cd "$abspath" && pwd -P)
+		dirname=$(cd "$abspath" >/dev/null && pwd -P)
 		abspath=$dirname
 	elif [[ -e $abspath ]]; then
-		dirname=$(cd "${abspath%/*}/" 2>/dev/null && pwd -P)
+		dirname=$(cd "${abspath%/*}/" >/dev/null 2>/dev/null && pwd -P)
 		abspath=$dirname/${abspath##*/}
 	fi
 
@@ -560,7 +560,7 @@ stage_rekeyed_files() {
 	encrypted_files=$(git ls-crypt)
 	if [[ $encrypted_files ]] && [[ $IS_BARE == 'false' ]]; then
 		# touch all encrypted files to prevent stale stat info
-		cd "$REPO" || die 1 'could not change into the "%s" directory' "$REPO"
+		cd "$REPO" >/dev/null || die 1 'could not change into the "%s" directory' "$REPO"
 		# shellcheck disable=SC2086
 		touch $encrypted_files
 		# shellcheck disable=SC2086
@@ -740,7 +740,7 @@ force_checkout() {
 		# but we already made sure the repo was clean during the safety checks
 		local encrypted_files
 		encrypted_files=$(git "ls-crypt-${CONTEXT}")
-		cd "$REPO" || die 1 'could not change into the "%s" directory' "$REPO"
+		cd "$REPO" >/dev/null || die 1 'could not change into the "%s" directory' "$REPO"
 		IFS=$'\n'
 		for file in $encrypted_files; do
 			rm -f "$file"
@@ -835,7 +835,7 @@ uninstall_transcrypt() {
 		local encrypted_files
 		encrypted_files=$(git ls-crypt)
 		if [[ $encrypted_files ]] && [[ $IS_BARE == 'false' ]]; then
-			cd "$REPO" || die 1 'could not change into the "%s" directory' "$REPO"
+			cd "$REPO" >/dev/null || die 1 'could not change into the "%s" directory' "$REPO"
 			# shellcheck disable=SC2086
 			touch $encrypted_files
 		fi
@@ -963,7 +963,7 @@ upgrade_transcrypt() {
 # list all of the currently encrypted files in the repository
 list_files() {
 	if [[ $IS_BARE == 'false' ]]; then
-		cd "$REPO" || die 1 'could not change into the "%s" directory' "$REPO"
+		cd "$REPO" >/dev/null || die 1 'could not change into the "%s" directory' "$REPO"
 		git -c core.quotePath=false ls-files | git -c core.quotePath=false check-attr --stdin filter | awk 'BEGIN { FS = ":" }; /crypt/{ print $1 }'
 	fi
 }
